spring:
  application:
    name: gatewayService

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        - id: studentService
          uri: lb://studentService
          predicates:
            - Path=/studentService/**
          filters:
            - StripPrefix=1

      ## Service2
      - id: noteService
        uri: lb://noteService
        predicates:
          - Path=/noteService/**
        filters:
          - StripPrefix=2
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
